spring.application.name=Pg3-backend

server.port=4494
## Set the db URL
#spring.datasource.url=jdbc:h2:mem:testdb
## Set the username to sa
#spring.datasource.username=sa
## Set a blank password
#spring.datasource.password=
#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=estateagentsx;encrypt=true;trustServerCertificate=true
#spring.datasource.username=pvm
#spring.datasource.password=pvm
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=estateagents
spring.datasource.username=pvm
spring.datasource.password=prav
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update